name: KV Sync

on:
  schedule:
    - cron: "0 0 * * *" # setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm i node-fetch@3

      - name: Pull source and push KV
        env:
          PROXY_BANK_URL: ${{ vars.PROXY_BANK_URL }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ vars.CF_ACCOUNT_ID }}
          CF_NAMESPACE_ID: ${{ vars.CF_NAMESPACE_ID }}
        run: node scripts/push-kv.js
